### PR TITLE
Private events feature

### PR DESCRIPTION
**Pull request by edemagbenyo**
### 😎

### CODE REVIEW

**Review by mcrd25 — CHANGES_REQUESTED** [review]
# Changes Required! Almost There 🔍 👀 

Hi @edemagbenyo and @Grifo89 👋 ,

I looked at the previous PRs and you have done a good job implementing the changes recommended by the previous reviews!

There is one hard requirement still left to address:

### Required Changes
- The User's show page should show events they created as well as events they are attending (separated into past and upcoming). Currently, you only show events they are attending separated into past and upcoming. This requirement can be seen from this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) and this screenshot: 
Screen Shot 2020-01-15 at 10 24 16 PM
 from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations).

***Please makes changes and submit another review request.
If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Comment by Grifo89** [comment]
Requirement added.

**Review by efrapp — APPROVED** [review]
## Hi @edemagbenyo  and @Grifo89  👋
Guy, great job completing the suggestion from the last code review. I think you are done with this project, however, I left you some (optional) comments below regarding some behaviors I observed in your app.

### Optional changes
- [ ] Currently, the app lets a user attends an event in the past but in a real-world app that shouldn't happen
- [ ] when I signup with a user2 (a user1 was created previously) the `My Events` link in the navbar always points to the user1. Maybe you can use the `current_user` to fix this.

You can merge this PR and move on 👍. Congratulations!

**Status:** `Approved`

**Comment by Grifo89** [comment]
Hey @efrapp, can you please update our status to project approved? Thanks

**Comment by efrapp** [comment]
Hi @Grifo89, how are you?
The PR was already approved here on Github. Are you talking about the status in the Microverse dashboard? Let me know, please.

**Comment by Grifo89** [comment]
Yes @efrapp, on the Microverse progress view. There appears as changes required

**Comment by efrapp** [comment]
Ok, @Grifo89 give me some time please to fix the problem. Thank you.

**Comment by Grifo89** [comment]
@efrapp thank you so much.

**Comment by efrapp** [comment]
@Grifo89 I already reported the issue with the Microverse staff. I will update you when I get a response.

**Comment by efrapp** [comment]
Hi @Grifo89,
The status in the dashboard should be fine now. Can you check it, please?

**Pull request merged**
